<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="12" passed="5" failed="7" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-08T16:55:35 IST" name="Capstone Suite" finished-at="2025-09-08T17:00:55 IST" duration-ms="320189">
    <groups>
    </groups>
    <test started-at="2025-09-08T16:55:35 IST" name="NopCommerce Tests" finished-at="2025-09-08T17:00:55 IST" duration-ms="320189">
      <class name="com.capstone.tests.ProductSearchTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.ProductSearchTest@10aa41f2]" started-at="2025-09-08T17:00:37 IST" name="setUp" finished-at="2025-09-08T17:00:40 IST" duration-ms="2507" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.ProductSearchTest.loginTest() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTest()[pri:0, instance:com.capstone.tests.ProductSearchTest@10aa41f2]" started-at="2025-09-08T17:00:40 IST" name="loginTest" finished-at="2025-09-08T17:00:55 IST" duration-ms="15345" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.capstone.tests.ProductSearchTest.loginTest(ProductSearchTest.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.ProductSearchTest@10aa41f2]" started-at="2025-09-08T17:00:55 IST" name="logResult" finished-at="2025-09-08T17:00:55 IST" duration-ms="228" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=ProductSearchTest.loginTest()[pri:0, instance:com.capstone.tests.ProductSearchTest@10aa41f2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- com.capstone.tests.ProductSearchTest -->
      <class name="com.capstone.tests.CartTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.CartTest@757277dc]" started-at="2025-09-08T16:57:47 IST" name="setUp" finished-at="2025-09-08T16:57:49 IST" duration-ms="2012" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.CartTest.cartTest() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="cartTest()[pri:0, instance:com.capstone.tests.CartTest@757277dc]" started-at="2025-09-08T16:57:49 IST" name="cartTest" finished-at="2025-09-08T16:58:04 IST" duration-ms="15531" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.capstone.tests.CartTest.cartTest(CartTest.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cartTest -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.CartTest@757277dc]" started-at="2025-09-08T16:58:04 IST" name="logResult" finished-at="2025-09-08T16:58:04 IST" duration-ms="176" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=cartTest status=FAILURE method=CartTest.cartTest()[pri:0, instance:com.capstone.tests.CartTest@757277dc] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- com.capstone.tests.CartTest -->
      <class name="com.capstone.tests.RegisterTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.RegisterTest@49e5f737]" started-at="2025-09-08T16:57:05 IST" name="setUp" finished-at="2025-09-08T16:57:07 IST" duration-ms="2066" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.RegisterTest.registerNewUser() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="registerNewUser()[pri:0, instance:com.capstone.tests.RegisterTest@49e5f737]" started-at="2025-09-08T16:57:07 IST" name="registerNewUser" finished-at="2025-09-08T16:57:29 IST" duration-ms="21740" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerNewUser -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.RegisterTest@49e5f737]" started-at="2025-09-08T16:57:29 IST" name="logResult" finished-at="2025-09-08T16:57:29 IST" duration-ms="215" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=registerNewUser status=SUCCESS method=RegisterTest.registerNewUser()[pri:0, instance:com.capstone.tests.RegisterTest@49e5f737] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- com.capstone.tests.RegisterTest -->
      <class name="com.capstone.tests.AddressTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.AddressTest@5c671d7f]" started-at="2025-09-08T16:57:29 IST" name="setUp" finished-at="2025-09-08T16:57:31 IST" duration-ms="2001" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.AddressTest.addNewAddress() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addNewAddress()[pri:0, instance:com.capstone.tests.AddressTest@5c671d7f]" started-at="2025-09-08T16:57:31 IST" name="addNewAddress" finished-at="2025-09-08T16:57:46 IST" duration-ms="15513" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.capstone.tests.AddressTest.addNewAddress(AddressTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewAddress -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.AddressTest@5c671d7f]" started-at="2025-09-08T16:57:46 IST" name="logResult" finished-at="2025-09-08T16:57:47 IST" duration-ms="181" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewAddress status=FAILURE method=AddressTest.addNewAddress()[pri:0, instance:com.capstone.tests.AddressTest@5c671d7f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- com.capstone.tests.AddressTest -->
      <class name="com.capstone.tests.E2ERegisterTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.E2ERegisterTest@c86b9e3]" started-at="2025-09-08T16:58:58 IST" name="setUp" finished-at="2025-09-08T16:59:01 IST" duration-ms="2936" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.E2ERegisterTest.testEndToEndEcommerceFlow() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testEndToEndEcommerceFlow()[pri:0, instance:com.capstone.tests.E2ERegisterTest@c86b9e3]" started-at="2025-09-08T16:59:01 IST" name="testEndToEndEcommerceFlow" finished-at="2025-09-08T17:00:37 IST" duration-ms="95891" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEndToEndEcommerceFlow -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.E2ERegisterTest@c86b9e3]" started-at="2025-09-08T17:00:37 IST" name="logResult" finished-at="2025-09-08T17:00:37 IST" duration-ms="242" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testEndToEndEcommerceFlow status=SUCCESS method=E2ERegisterTest.testEndToEndEcommerceFlow()[pri:0, instance:com.capstone.tests.E2ERegisterTest@c86b9e3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- com.capstone.tests.E2ERegisterTest -->
      <class name="com.capstone.tests.ChangePasswordTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.ChangePasswordTest@687e99d8]" started-at="2025-09-08T16:58:04 IST" name="setUp" finished-at="2025-09-08T16:58:06 IST" duration-ms="1895" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.ChangePasswordTest.PasswordTest() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="PasswordTest()[pri:0, instance:com.capstone.tests.ChangePasswordTest@687e99d8]" started-at="2025-09-08T16:58:06 IST" name="PasswordTest" finished-at="2025-09-08T16:58:22 IST" duration-ms="16021" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.capstone.tests.ChangePasswordTest.PasswordTest(ChangePasswordTest.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PasswordTest -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.ChangePasswordTest@687e99d8]" started-at="2025-09-08T16:58:22 IST" name="logResult" finished-at="2025-09-08T16:58:22 IST" duration-ms="209" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=PasswordTest status=FAILURE method=ChangePasswordTest.PasswordTest()[pri:0, instance:com.capstone.tests.ChangePasswordTest@687e99d8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- com.capstone.tests.ChangePasswordTest -->
      <class name="com.capstone.tests.E2ELoginTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.E2ELoginTest@6aaceffd]" started-at="2025-09-08T16:58:41 IST" name="setUp" finished-at="2025-09-08T16:58:43 IST" duration-ms="1976" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.E2ELoginTest.testEndToEndEcommerceFlow() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testEndToEndEcommerceFlow()[pri:0, instance:com.capstone.tests.E2ELoginTest@6aaceffd]" started-at="2025-09-08T16:58:43 IST" name="testEndToEndEcommerceFlow" finished-at="2025-09-08T16:58:58 IST" duration-ms="15462" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.capstone.tests.E2ELoginTest.testEndToEndEcommerceFlow(E2ELoginTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEndToEndEcommerceFlow -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.E2ELoginTest@6aaceffd]" started-at="2025-09-08T16:58:58 IST" name="logResult" finished-at="2025-09-08T16:58:58 IST" duration-ms="212" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testEndToEndEcommerceFlow status=FAILURE method=E2ELoginTest.testEndToEndEcommerceFlow()[pri:0, instance:com.capstone.tests.E2ELoginTest@6aaceffd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- com.capstone.tests.E2ELoginTest -->
      <class name="com.capstone.tests.LoginTest">
        <test-method is-config="true" signature="setupReport()[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:55:35 IST" name="setupReport" finished-at="2025-09-08T16:55:35 IST" duration-ms="216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupReport -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:55:35 IST" name="setUp" finished-at="2025-09-08T16:55:38 IST" duration-ms="2962" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.LoginTest.loginTestBlankCredentials() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTestBlankCredentials()[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:55:38 IST" name="loginTestBlankCredentials" finished-at="2025-09-08T16:55:42 IST" duration-ms="3859" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestBlankCredentials -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:55:42 IST" name="logResult" finished-at="2025-09-08T16:55:42 IST" duration-ms="193" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTestBlankCredentials status=SUCCESS method=LoginTest.loginTestBlankCredentials()[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:55:42 IST" name="setUp" finished-at="2025-09-08T16:55:44 IST" duration-ms="1774" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.LoginTest.loginTestInvalidEmail() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTestInvalidEmail()[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:55:44 IST" name="loginTestInvalidEmail" finished-at="2025-09-08T16:56:09 IST" duration-ms="25350" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestInvalidEmail -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:56:09 IST" name="logResult" finished-at="2025-09-08T16:56:10 IST" duration-ms="200" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTestInvalidEmail status=SUCCESS method=LoginTest.loginTestInvalidEmail()[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:56:10 IST" name="setUp" finished-at="2025-09-08T16:56:12 IST" duration-ms="2032" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.LoginTest.loginTestInvalidPassword() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTestInvalidPassword()[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:56:12 IST" name="loginTestInvalidPassword" finished-at="2025-09-08T16:56:37 IST" duration-ms="25528" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestInvalidPassword -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:56:37 IST" name="logResult" finished-at="2025-09-08T16:56:37 IST" duration-ms="191" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTestInvalidPassword status=SUCCESS method=LoginTest.loginTestInvalidPassword()[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:56:37 IST" name="setUp" finished-at="2025-09-08T16:56:39 IST" duration-ms="2045" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.LoginTest.loginTestValidCredentials() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTestValidCredentials()[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:56:39 IST" name="loginTestValidCredentials" finished-at="2025-09-08T16:57:05 IST" duration-ms="25341" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed: Login was unsuccessful. Please correct the errors and try again.
No customer account found expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed: Login was unsuccessful. Please correct the errors and try again.
No customer account found expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.capstone.tests.LoginTest.loginTestValidCredentials(LoginTest.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestValidCredentials -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T16:57:05 IST" name="logResult" finished-at="2025-09-08T16:57:05 IST" duration-ms="168" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTestValidCredentials status=FAILURE method=LoginTest.loginTestValidCredentials()[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
        <test-method is-config="true" signature="tearDownReport()[pri:0, instance:com.capstone.tests.LoginTest@26b3fd41]" started-at="2025-09-08T17:00:55 IST" name="tearDownReport" finished-at="2025-09-08T17:00:56 IST" duration-ms="485" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownReport -->
      </class> <!-- com.capstone.tests.LoginTest -->
      <class name="com.capstone.tests.CheckoutTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.capstone.tests.CheckoutTest@e4487af]" started-at="2025-09-08T16:58:22 IST" name="setUp" finished-at="2025-09-08T16:58:24 IST" duration-ms="2037" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.capstone.tests.CheckoutTest.cartTest() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="cartTest()[pri:0, instance:com.capstone.tests.CheckoutTest@e4487af]" started-at="2025-09-08T16:58:24 IST" name="cartTest" finished-at="2025-09-08T16:58:40 IST" duration-ms="15909" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.capstone.tests.CheckoutTest.cartTest(CheckoutTest.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cartTest -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:com.capstone.tests.CheckoutTest@e4487af]" started-at="2025-09-08T16:58:40 IST" name="logResult" finished-at="2025-09-08T16:58:41 IST" duration-ms="194" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=cartTest status=FAILURE method=CheckoutTest.cartTest()[pri:0, instance:com.capstone.tests.CheckoutTest@e4487af] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- com.capstone.tests.CheckoutTest -->
    </test> <!-- NopCommerce Tests -->
  </suite> <!-- Capstone Suite -->
</testng-results>
